name: main

on:
  push:
    branches:
      - main
      - master
  pull_request:
    branches:
      - main
      - master

jobs:
  lint:
    uses: ./.github/workflows/_lint.yml
    permissions:
      checks: write
      contents: write

  check-secrets: # thx https://stackoverflow.com/a/70249520/6612932
    runs-on: ubuntu-latest

    needs: lint

    outputs:
      caprover-server: ${{ steps.caprover-server.outputs.defined }}

    steps:
      - name: Check for secrets.CAPROVER_SERVER availability
        id: caprover-server
        # perform secret check & put boolean result as an output
        shell: bash
        run: |
          if [ "${{ secrets.CAPROVER_SERVER }}" != '' ]; then
            echo "defined=true" >> $GITHUB_OUTPUT;
          else
            echo "defined=false" >> $GITHUB_OUTPUT;
          fi

  
